---
kind: Service
apiVersion: v1
metadata:
  name: airflow-rabbitmq-svc
  labels:
    app: airflow-broker
spec:
  type: NodePort
  selector:
    app: airflow-broker
  ports:
  - name: http
    protocol: TCP
    port: 15672
    targetPort: http
    nodePort: 32362
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: amqp
    nodePort: 32352
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: airflow-rabbitmq-sts
  labels:
    app: airflow-broker
spec:
  serviceName: airflow-rabbitmq-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow-broker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: compute
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
        env:
          - name: RABBITMQ_DEFAULT_VHOST
            value: rabbit
          - name: RABBITMQ_DEFAULT_USER
            value: airflow-njuics
          - name: RABBITMQ_DEFAULT_PASS
            value: airflow-njuics
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "-l", "node_health_check"]
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 15
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 20
          periodSeconds: 60
          timeoutSeconds: 10