apiVersion: v1
kind: Service
metadata:
  name: airflow-redis-svc
spec:
  type: NodePort
  selector:
    app: airflow-redis
  ports:
  - name: http
    protocol: TCP
    port: 6379
    targetPort: redis
    nodePort: 32379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-redis-deploy
  labels:
    app: airflow-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-redis
  template:
    metadata:
      labels:
        app: airflow-redis
    spec:
      volumes:
      - name: redis-health-script
        configMap:
          name: airflow-redis-script
          defaultMode: 0755
      containers:
      - name: compute
        image: "redis:4.0-alpine"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: redis-health-script
          mountPath: /health
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - sh
            - -c
            - /health/ping_local.sh
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - sh
            - -c
            - /health/ping_local.sh
