apiVersion: v1
kind: Service
metadata:
  name: airflow-postgresql-svc
  labels:
    app: airflow-postgresql
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: airflow-postgresql
