apiVersion: v1
kind: Service
metadata:
  name: airflow-ui-svc
spec:
  type: NodePort
  selector:
    app: airflow-ui
  ports:
  - name: airflow
    protocol: TCP
    port: 8080
    targetPort: airflow
    nodePort: 32380
  - name: flower
    protocol: TCP
    port: 5555
    targetPort: flower
    nodePort: 32355